### ISSUE TITLE
ArtifactPayloadGenerator.cna script bug

### ISSUE THREAD

**Issue by WBGlIl** [harleyQu1nn/AggressorScripts#10]
My English is bad
```
$listener_name = lc($name);
if ($listener_name hasmatch "http" || $listener_name hasmatch "https")
```
If the listener name does not contain HTTP or HTTPS, it will fail.
Can use the listener_info function
This will get the type of listener
```
$listener_name = listener_info($name);
if ($listener_name hasmatch "http" || $listener_name hasmatch "https") {
......
}
else{
.......
}
```

**Comment by harleyQu1nn** [comment]
Going to fix this with drow_listener function in a future release. Thanks!
