### ISSUE TITLE
Case sensitive process matches for ProcessColor.cna ?

### ISSUE THREAD

**Issue by qgrosperrin** [harleyQu1nn/AggressorScripts#8]
Is the string comparison case sensitive ? I have seen a number of hosts where 'cb.exe' processes were not properly highlighted in red. I think that also happened for Tanium processes a couple times.

**Comment by qgrosperrin** [comment]
Thanks for the script btw ! Really like it :)

**Comment by harleyQu1nn** [comment]
These processes have to be exact matches. I fixed the cb.exe mishap though so thanks for pointing that one out! Closing this out.
